from fastapi.responses import HTMLResponse

HTML='''<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>HaberRSS Control Center</title><style>
:root{--bg:#080b12;--panel:#111722;--line:#202a39;--text:#edf2f7;--muted:#8793a6;--good:#3ddc97;--bad:#ff6678;--warn:#ffca5c;--accent:#7c8cff}*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font-family:Inter,system-ui,sans-serif}header{padding:22px 28px;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center;position:sticky;top:0;background:#080b12ee;backdrop-filter:blur(10px);z-index:5}h1{font-size:21px;margin:0}.muted{color:var(--muted);font-size:12px}.wrap{padding:24px;max-width:1500px;margin:auto}.tabs{display:flex;gap:8px;margin-bottom:18px;flex-wrap:wrap}.tab{border:1px solid var(--line);background:var(--panel);color:var(--muted);padding:9px 13px;border-radius:9px;cursor:pointer}.tab.active{color:#fff;border-color:var(--accent)}.grid{display:grid;grid-template-columns:repeat(6,minmax(130px,1fr));gap:12px}.card{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:15px}.num{font-size:28px;font-weight:800;margin-top:7px}.ok{color:var(--good)}.bad{color:var(--bad)}.warn{color:var(--warn)}section{margin-top:22px}.panel{background:var(--panel);border:1px solid var(--line);border-radius:14px;overflow:hidden}table{width:100%;border-collapse:collapse}th,td{padding:11px 13px;border-bottom:1px solid var(--line);font-size:13px;text-align:left}th{color:var(--muted);font-weight:600}.score{font-weight:800}.bar{height:6px;background:#252e3d;border-radius:10px;overflow:hidden}.bar i{display:block;height:100%;background:var(--accent)}.row{display:grid;grid-template-columns:1fr 1fr;gap:14px}.item{padding:14px;border-bottom:1px solid var(--line)}button{background:#1a2230;border:1px solid var(--line);color:#fff;padding:8px 11px;border-radius:8px;cursor:pointer}.pill{padding:4px 7px;border-radius:20px;background:#202938;color:var(--muted);font-size:11px}.hidden{display:none}@media(max-width:900px){.grid{grid-template-columns:repeat(2,1fr)}.row{grid-template-columns:1fr}}@media(max-width:500px){.wrap{padding:14px}}
</style></head><body><header><div><h1>HaberRSS · Control Center</h1><span class="muted">Real-time News Intelligence</span></div><div id="system">● checking</div></header><main class="wrap"><nav class="tabs"><button class="tab active" onclick="show('dashboard',this)">Genel Bakış</button><button class="tab" onclick="show('trends',this)">Viral Radar</button><button class="tab" onclick="show('sources',this)">Kaynaklar</button><button class="tab" onclick="show('telegram',this)">Telegram</button><button class="tab" onclick="show('diagnostics',this)">Sistem Sağlığı</button><button class="tab" onclick="show('fix',this)">Sorun Çözücü</button><button class="tab" onclick="show('activity',this)">Akış</button></nav>
<div id="dashboard"><div id="cards" class="grid"></div><section><div class="row"><div class="panel"><div class="item"><b>Viral Alarm Akışı</b><div class="muted">En yüksek potansiyelli olaylar</div></div><div id="mini"></div></div><div class="panel"><div class="item"><b>Operasyon Durumu</b><div id="ops" class="muted">yükleniyor...</div></div></div></div></section></div>
<div id="trends" class="hidden"><section><div class="panel"><table><thead><tr><th>Skor</th><th>Olay</th><th>Kategori</th><th>Haber</th><th>Kaynak</th><th>İvme</th><th>Durum</th></tr></thead><tbody id="trendrows"></tbody></table></div></section></div>
<div id="sources" class="hidden"><section><div class="panel"><table><thead><tr><th>Kaynak</th><th>Kategori</th><th>Aktif</th><th>Ağırlık</th><th>Son başarı</th><th>Hatalar</th></tr></thead><tbody id="sourcerows"></tbody></table></div></section></div>
<div id="telegram" class="hidden"><section><div id="tgbox" class="panel"></div></section></div>
<div id="diagnostics" class="hidden"><section><button onclick="loadAll()">↻ Yenile</button><div id="diag" class="panel" style="margin-top:12px"></div></section></div>
<div id="fix" class="hidden"><section><div id="fixbox" class="panel"></div></section></div>
<div id="activity" class="hidden"><section><div class="panel"><table><thead><tr><th>Zaman</th><th>Başlık</th><th>Kaynak</th><th>Skor</th><th>Durum</th></tr></thead><tbody id="activityrows"></tbody></table></div></section></div>
</main><script>
let token=localStorage.getItem('haber_admin_token')||prompt('ADMIN_TOKEN');if(token)localStorage.setItem('haber_admin_token',token);const H={'X-Admin-Token':token};
const esc=x=>String(x??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function get(u){let r=await fetch(u,{headers:H});if(!r.ok)throw Error(await r.text());return r.json()}
function show(id,el){document.querySelectorAll('main>div').forEach(x=>x.classList.add('hidden'));document.getElementById(id).classList.remove('hidden');document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));el.classList.add('active');loadAll()}
async function loadAll(){try{let o=await get('/api/admin/overview');cards.innerHTML=Object.entries(o).map(([k,v])=>`<div class="card"><div class="muted">${esc(k.replaceAll('_',' '))}</div><div class="num">${v}</div></div>`).join('');let t=await get('/api/admin/breaking?limit=30');trendrows.innerHTML=t.map(x=>`<tr><td class="score ${x.viral_score>=75?'bad':''}">${Number(x.viral_score).toFixed(1)}</td><td>${esc(x.canonical_title)}</td><td>${esc(x.category)}</td><td>${x.article_count}</td><td>${x.source_count}</td><td><div class="bar"><i style="width:${Math.min(100,Number(x.velocity_score)||0)}%"></i></div></td><td><span class="pill">${esc(x.state)}</span></td></tr>`).join('');mini.innerHTML=t.slice(0,5).map(x=>`<div class="item"><b>${Number(x.viral_score).toFixed(0)}</b> · ${esc(x.canonical_title)}<div class="muted">${x.source_count} kaynak · ${x.article_count} haber</div></div>`).join('');let s=await get('/api/admin/sources');sourcerows.innerHTML=s.map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.category)}</td><td class="${x.active?'ok':'bad'}">${x.active?'AKTİF':'PASİF'}</td><td>${x.weight}</td><td>${esc(x.last_success_at||'-')}</td><td class="${x.consecutive_errors?'warn':''}">${x.consecutive_errors}</td></tr>`).join('');let tg=await get('/api/admin/telegram');tgbox.innerHTML=`<div class="item"><b>Telegram Listener</b><div class="num ${tg.configured?'ok':'bad'}">${tg.configured?'HAZIR':'YAPILANDIRILMADI'}</div><div class="muted">Kanallar: ${tg.channels.map(esc).join(', ')||'-'} · Son 1 saat: ${tg.articles_1h} sinyal · Aktif kaynak: ${tg.active_sources}</div></div>`;let d=await get('/api/admin/diagnostics');diag.innerHTML=Object.entries(d).map(([k,v])=>`<div class="item"><b>${esc(k)}</b><pre style="white-space:pre-wrap;color:var(--muted)">${esc(typeof v==='object'?JSON.stringify(v,null,2):v)}</pre></div>`).join('');let f=await get('/api/admin/troubleshooter');fixbox.innerHTML=`<div class="item"><b>${f.issue_count} sorun tespit edildi</b></div>`+(f.issues.length?f.issues.map(x=>`<div class="item"><span class="pill">${esc(x.severity)}</span> <b>${esc(x.component)}</b><div>${esc(x.problem)}</div><div class="muted">Çözüm: ${esc(x.fix)}</div></div>`).join(''):'<div class="item ok">Sistem temiz görünüyor.</div>');let a=await get('/api/admin/activity?limit=50');activityrows.innerHTML=a.map(x=>`<tr><td>${esc(x.discovered_at)}</td><td>${esc(x.title)}</td><td>${esc(x.source)}</td><td class="score">${Number(x.viral_score).toFixed(1)}</td><td>${esc(x.state)}</td></tr>`).join('');system.innerHTML=d.status==='healthy'?'<span class="ok">● HEALTHY</span>':'<span class="bad">● DEGRADED</span>';ops.innerHTML=`PostgreSQL: <span class="ok">OK</span><br>Redis: ${d.redis?.ok?'<span class="ok">OK</span>':'<span class="bad">ERROR</span>'}<br>Aktif cluster: ${d.active_clusters}<br>Son 5 dk haber: ${d.articles_5m}`;}catch(e){system.innerHTML='<span class="bad">● PANEL ERROR</span>';console.error(e)}}loadAll();setInterval(loadAll,15000);
</script></body></html>'''
def dashboard(): return HTMLResponse(HTML)
