# Search feeds are intentionally broad: they catch stories before a single publisher becomes dominant.
SOURCES = [
    ("Google News Türkiye", "https://news.google.com/rss?hl=tr&gl=TR&ceid=TR:tr", "genel"),
    ("Google News Son Dakika", "https://news.google.com/rss/search?q=son%20dakika&hl=tr&gl=TR&ceid=TR:tr", "son-dakika"),
    ("Google News Gündem", "https://news.google.com/rss/search?q=Türkiye%20gündem&hl=tr&gl=TR&ceid=TR:tr", "gundem"),
    ("Google News Siyaset", "https://news.google.com/rss/search?q=siyaset%20Türkiye&hl=tr&gl=TR&ceid=TR:tr", "siyaset"),
    ("Google News Ekonomi", "https://news.google.com/rss/search?q=Türkiye%20ekonomi&hl=tr&gl=TR&ceid=TR:tr", "ekonomi"),
    ("Google News Spor", "https://news.google.com/rss/search?q=spor%20Türkiye&hl=tr&gl=TR&ceid=TR:tr", "spor"),
    ("Google News Teknoloji", "https://news.google.com/rss/search?q=teknoloji%20Türkiye&hl=tr&gl=TR&ceid=TR:tr", "teknoloji"),
    ("Google News Magazin", "https://news.google.com/rss/search?q=magazin%20Türkiye&hl=tr&gl=TR&ceid=TR:tr", "magazin"),
    ("Google News Dünya", "https://news.google.com/rss/search?q=dünya%20gündem&hl=tr&gl=TR&ceid=TR:tr", "dunya"),
    ("Google News Deprem", "https://news.google.com/rss/search?q=deprem%20Türkiye&hl=tr&gl=TR&ceid=TR:tr", "afet"),
    ("Google News Yangın", "https://news.google.com/rss/search?q=yangın%20Türkiye&hl=tr&gl=TR&ceid=TR:tr", "afet"),
    ("Google News Kaza", "https://news.google.com/rss/search?q=kaza%20Türkiye&hl=tr&gl=TR&ceid=TR:tr", "afet"),
    ("Google News Patlama", "https://news.google.com/rss/search?q=patlama%20Türkiye&hl=tr&gl=TR&ceid=TR:tr", "afet"),
    ("Google News Hava Durumu", "https://news.google.com/rss/search?q=sel%20fırtına%20kar%20Türkiye&hl=tr&gl=TR&ceid=TR:tr", "hava"),
    ("Google News Son Gelişme", "https://news.google.com/rss/search?q=son%20gelişme%20Türkiye&hl=tr&gl=TR&ceid=TR:tr", "breaking"),
    ("Google News Flaş", "https://news.google.com/rss/search?q=flaş%20Türkiye&hl=tr&gl=TR&ceid=TR:tr", "breaking"),
    ("Google News Önemli", "https://news.google.com/rss/search?q=önemli%20gelişme%20Türkiye&hl=tr&gl=TR&ceid=TR:tr", "breaking"),
    ("Google News Fenerbahçe", "https://news.google.com/rss/search?q=Fenerbahçe&hl=tr&gl=TR&ceid=TR:tr", "spor"),
    ("Google News Galatasaray", "https://news.google.com/rss/search?q=Galatasaray&hl=tr&gl=TR&ceid=TR:tr", "spor"),
    ("Google News Beşiktaş", "https://news.google.com/rss/search?q=Beşiktaş&hl=tr&gl=TR&ceid=TR:tr", "spor"),
    ("Google News Trabzonspor", "https://news.google.com/rss/search?q=Trabzonspor&hl=tr&gl=TR&ceid=TR:tr", "spor"),
    ("Google News Milli Takım", "https://news.google.com/rss/search?q=Milli%20Takım%20Türkiye&hl=tr&gl=TR&ceid=TR:tr", "spor"),
    ("Google News Yapay Zeka", "https://news.google.com/rss/search?q=yapay%20zeka&hl=tr&gl=TR&ceid=TR:tr", "teknoloji"),
    ("Google News Bitcoin", "https://news.google.com/rss/search?q=Bitcoin%20Türkiye&hl=tr&gl=TR&ceid=TR:tr", "finans"),
    ("Google News Borsa", "https://news.google.com/rss/search?q=Borsa%20İstanbul&hl=tr&gl=TR&ceid=TR:tr", "finans"),
    ("Google News Dolar", "https://news.google.com/rss/search?q=dolar%20TL&hl=tr&gl=TR&ceid=TR:tr", "finans"),
    ("Google News Akaryakıt", "https://news.google.com/rss/search?q=akaryakıt%20zam%20Türkiye&hl=tr&gl=TR&ceid=TR:tr", "ekonomi"),
    ("Google News Zam", "https://news.google.com/rss/search?q=zam%20Türkiye&hl=tr&gl=TR&ceid=TR:tr", "ekonomi"),
    ("Google News Mahkeme", "https://news.google.com/rss/search?q=mahkeme%20karar%20Türkiye&hl=tr&gl=TR&ceid=TR:tr", "gundem"),
    ("Google News Tutuklama", "https://news.google.com/rss/search?q=tutuklandı%20Türkiye&hl=tr&gl=TR&ceid=TR:tr", "gundem"),
    ("Google News İstifa", "https://news.google.com/rss/search?q=istifa%20Türkiye&hl=tr&gl=TR&ceid=TR:tr", "gundem"),
]
